In [1]:
import numpy as np
import pandas as pd
pd.set_option('display.max_rows', None)

In [2]:
merged = pd.read_csv("./data/merged.csv")

In [3]:
merged.head()

,Unnamed: 0,id_invoice,issue_date,due_date,paid_date,paid,contact_id,total,amount_due,exchange_rate,...,id_invoice_info,description,item_code,quantity,id,name,is_supplier,is_customer,email,phone
0,0,90381d5a-9348-4208-915c-60b082378370,2021-01-31T00:00:00.000Z,2021-02-06T00:00:00.000Z,2021-02-06T00:00:00.000Z,True,8e81fbc4-4f33-4ae9-bf5e-a2415372e77b,174.8,0.0,1.0,...,a90834f9-90b5-4342-9cb6-f8d45b35fd7e,Rental income,NaN,1.0,8e81fbc4-4f33-4ae9-bf5e-a2415372e77b,Snow White,False,True,NaN,NaN
1,1,3dec381c-7af5-436d-8b35-2d3a69b95f89,2021-02-28T00:00:00.000Z,2021-03-06T00:00:00.000Z,2021-03-06T00:00:00.000Z,True,8e81fbc4-4f33-4ae9-bf5e-a2415372e77b,174.8,0.0,1.0,...,3554bf7d-bd10-449c-b05a-5a5e478bab73,Rental income,NaN,1.0,8e81fbc4-4f33-4ae9-bf5e-a2415372e77b,Snow White,False,True,NaN,NaN
2,2,0222b396-f017-4a90-ad5b-4a8e241d4afc,2021-03-31T00:00:00.000Z,2021-04-06T00:00:00.000Z,2021-04-06T00:00:00.000Z,True,8e81fbc4-4f33-4ae9-bf5e-a2415372e77b,174.8,0.0,1.0,...,1e35c6e6-456d-4dae-9d7f-c4ee6b15c06e,Rental income,NaN,1.0,8e81fbc4-4f33-4ae9-bf5e-a2415372e77b,Snow White,False,True,NaN,NaN
3,3,eb59789d-a21e-4628-a774-17a3bf38607b,2021-04-30T00:00:00.000Z,2021-05-06T00:00:00.000Z,2021-05-06T00:00:00.000Z,True,8e81fbc4-4f33-4ae9-bf5e-a2415372e77b,174.8,0.0,1.0,...,debf819e-83f7-41bf-9cef-1389fe2b5d94,Rental income,NaN,1.0,8e81fbc4-4f33-4ae9-bf5e-a2415372e77b,Snow White,False,True,NaN,NaN
4,4,87d4c9dc-f37a-43a2-8aab-40ba13f3a8ac,2021-05-31T00:00:00.000Z,2021-06-06T00:00:00.000Z,2021-06-06T00:00:00.000Z,True,8e81fbc4-4f33-4ae9-bf5e-a2415372e77b,174.8,0.0,1.0,...,f0e212e7-de75-4270-826f-50d5a75ce268,Rental income,NaN,1.0,8e81fbc4-4f33-4ae9-bf5e-a2415372e77b,Snow White,False,True,NaN,NaN

In [4]:
merged.columns

Index(['Unnamed: 0', 'id_invoice', 'issue_date', 'due_date', 'paid_date',
       'paid', 'contact_id', 'total', 'amount_due', 'exchange_rate',
       'currency', 'is_sale', 'invoice_id', 'id_invoice_info', 'description',
       'item_code', 'quantity', 'id', 'name', 'is_supplier', 'is_customer',
       'email', 'phone'],
      dtype='object')

In [5]:
# We need to create a word_dictionary for the df, we dont need the id cols and dates for the match, maybe only for return
merged.drop(["Unnamed: 0", "total", "amount_due", "id_invoice","exchange_rate", "issue_date", "due_date", "paid_date", "contact_id", "invoice_id", "id_invoice_info", "id"], axis=1, inplace=True)

In [6]:
merged.head()

,paid,currency,is_sale,description,item_code,quantity,name,is_supplier,is_customer,email,phone
0,True,GBP,True,Rental income,NaN,1.0,Snow White,False,True,NaN,NaN
1,True,GBP,True,Rental income,NaN,1.0,Snow White,False,True,NaN,NaN
2,True,GBP,True,Rental income,NaN,1.0,Snow White,False,True,NaN,NaN
3,True,GBP,True,Rental income,NaN,1.0,Snow White,False,True,NaN,NaN
4,True,GBP,True,Rental income,NaN,1.0,Snow White,False,True,NaN,NaN

In [7]:
# Create a dictionary where the keys are the columns and the values are the unique values in the cols
unique_values_dict = {}
for col in merged.columns:
    unique_values_dict[col] = merged[col].unique().tolist()

print(unique_values_dict)

{'paid': [True, False, nan], 'currency': ['GBP', 'NZD', 'ZAR', 'NGN', 'INR', nan], 'is_sale': [True, False, nan], 'description': ['Rental income', 'Rental Income for September', 'Rental Income', 'Tinkerbell cake', 'Purchase of building', 'Table', 'Baking Lessons', 'Zoo Chocolates StoredProviderCaching', 'Zoo Chocolates', 'Cinderella Cupcakes', 'Jasmine Cake', 'Frozen cupcakes', 'Ariel Cupcakes', 'Training', 'Bank Charges', 'Interest expense', 'Electricity', 'Electricity Increase once off payment', 'Salaries', 'Salaries overtime', 'Bashful Overtime', 'Payment; Bashful', 'Advertising Expense', 'Advertising expense', 'Advertising Expenses', 'Transport costs', 'Transit Costs', 'Repairs and Maintenance', 'Vehicle repairs', 'Purchase of Computer Equipment', 'Purchase of computer accessories', 'Purchase of baking Equipment', 'Scar Equipment - Maintenance', 'Maintenance', 'Computer Equipment', 'Packaging products', 'Packaging Materials', 'Grumpy Wages', 'Grumpy wages', 'Overtime', 'Potato', 'Capitalised', 'Computer Additions', 'Staff Party', 'Year end Party - Entertainment', 'Additional Office Machine', 'Consulting Fees', nan], 'item_code': [nan, 'TIN001', 'CHO001', 'CIN001', 'JAS001', 'FR001', 'ARI001'], 'quantity': [1.0, 10.0, 20.0, 100.0, 200.0, 500.0, 99.0, 60.0, 50.0, 220.0, 30.0, 45.0, 2.0, 150.0, 175.0, 55.0, 250.0, 15.0, 40.0, 400.0, 35.0, 130.0, 3.0, 450.0, 4.0, 1400.0, 300.0, 1750.0, 1000.0, 2000.0, nan], 'name': ['Snow White', 'Maleficent', 'Mrs Potts', 'Cindarella', 'Elsa Frozen', 'Anna Frozen 1', 'Ariel', 'Tinkerbell', 'Ariel new', 'Alice', 'Judy Hopps', 'Jasmine', 'Thomas Training', 'Captain Hook', 'Michelle Mitchell', 'Ele Kyriazis', 'Aladdin', 'Jafar Bank', 'Lumiere Electricity', 'Step Mother', 'Hans Prince', 'Bashful', 'Ursula', 'Gaston Advertising', 'Sir Miles Axlerod', 'Guido', 'Iago Cake', 'Scar Enterprises', 'Claude Frollo', 'Grumpy', 'Potato man', 'Dawn Bellwether', 'Shere Khan', 'Elle Elves', 'Gastonia', 'Frozen King', 'Anna Frozen 2', 'Aladdinn'], 'is_supplier': [False, True], 'is_customer': [True, False], 'email': [nan, 'frozen@mail.com', 'ariel@mail.com', 'aladdin@disney.com', 'aladdinn@disney.com'], 'phone': [nan]}

In [8]:
unique_values_dict["columns"] = list(merged.columns)

In [9]:
#Lets remove all the keys which have True and False values because you can't map back
filtered_dict = {key: value for key, value in unique_values_dict.items() if not any(isinstance(x, bool) for x in value)}
#making all the values strings
filtered_dict_str = {key: [str(x) for x in value] for key, value in filtered_dict.items()}
#converting all the values to lower case
# filtered_dict_str_lower = {}

# for key, values in filtered_dict_str.items():
#     new_values = []
#     for ind, value in enumerate(values):
#         if isinstance(value, str) and ind!=0:
#             new_values.append(value.lower())
#         else:
#             new_values.append(value)
#     filtered_dict_str_lower[key] = new_values

In [10]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
# nltk.download('wordnet')

# Initialize the WordNetLemmatizer
wnl = WordNetLemmatizer()
# nltk.download('omw-1.4')

In [11]:
# Function to tokenize and lemmatize a string
def tokenize_and_lemmatize(text):
    tokens = word_tokenize(text)
    lemmatized_tokens = [wnl.lemmatize(token.lower()) for token in tokens]
    return tokens, lemmatized_tokens

def handle_underscores(value):
    return value.split("_")

# Adding all the lemmatized and tokenized versions
augmented_dict = {}
for key, values in filtered_dict_str.items():
    augmented_list = []
    for value in values:
        # Handle original, tokenized and lemmatized versions
        original, tokenized, lemmatized = value, *tokenize_and_lemmatize(value)
        
        # Handle underscores
        underscore_handled = handle_underscores(value)
        
        # Aggregate all
        all_versions = [original, *tokenized, *lemmatized, *underscore_handled]
        
        augmented_list.append({value: all_versions})
    augmented_dict[key] = augmented_list

In [12]:
#We actually want to leave the repetitions in because it emphasizes full matches
augmented_dict

{'currency': [{'GBP': ['GBP', 'GBP', 'gbp', 'GBP']},
  {'NZD': ['NZD', 'NZD', 'nzd', 'NZD']},
  {'ZAR': ['ZAR', 'ZAR', 'zar', 'ZAR']},
  {'NGN': ['NGN', 'NGN', 'ngn', 'NGN']},
  {'INR': ['INR', 'INR', 'inr', 'INR']},
  {'nan': ['nan', 'nan', 'nan', 'nan']}],
 'description': [{'Rental income': ['Rental income',
    'Rental',
    'income',
    'rental',
    'income',
    'Rental income']},
  {'Rental Income for September': ['Rental Income for September',
    'Rental',
    'Income',
    'for',
    'September',
    'rental',
    'income',
    'for',
    'september',
    'Rental Income for September']},
  {'Rental Income': ['Rental Income',
    'Rental',
    'Income',
    'rental',
    'income',
    'Rental Income']},
  {'Tinkerbell cake': ['Tinkerbell cake',
    'Tinkerbell',
    'cake',
    'tinkerbell',
    'cake',
    'Tinkerbell cake']},
  {'Purchase of building': ['Purchase of building',
    'Purchase',
    'of',
    'building',
    'purchase',
    'of',
    'building',
    'Purchase of building']},
  {'Table': ['Table', 'Table', 'table', 'Table']},
  {'Baking Lessons': ['Baking Lessons',
    'Baking',
    'Lessons',
    'baking',
    'lesson',
    'Baking Lessons']},
  {'Zoo Chocolates StoredProviderCaching': ['Zoo Chocolates StoredProviderCaching',
    'Zoo',
    'Chocolates',
    'StoredProviderCaching',
    'zoo',
    'chocolate',
    'storedprovidercaching',
    'Zoo Chocolates StoredProviderCaching']},
  {'Zoo Chocolates': ['Zoo Chocolates',
    'Zoo',
    'Chocolates',
    'zoo',
    'chocolate',
    'Zoo Chocolates']},
  {'Cinderella Cupcakes': ['Cinderella Cupcakes',
    'Cinderella',
    'Cupcakes',
    'cinderella',
    'cupcake',
    'Cinderella Cupcakes']},
  {'Jasmine Cake': ['Jasmine Cake',
    'Jasmine',
    'Cake',
    'jasmine',
    'cake',
    'Jasmine Cake']},
  {'Frozen cupcakes': ['Frozen cupcakes',
    'Frozen',
    'cupcakes',
    'frozen',
    'cupcake',
    'Frozen cupcakes']},
  {'Ariel Cupcakes': ['Ariel Cupcakes',
    'Ariel',
    'Cupcakes',
    'ariel',
    'cupcake',
    'Ariel Cupcakes']},
  {'Training': ['Training', 'Training', 'training', 'Training']},
  {'Bank Charges': ['Bank Charges',
    'Bank',
    'Charges',
    'bank',
    'charge',
    'Bank Charges']},
  {'Interest expense': ['Interest expense',
    'Interest',
    'expense',
    'interest',
    'expense',
    'Interest expense']},
  {'Electricity': ['Electricity',
    'Electricity',
    'electricity',
    'Electricity']},
  {'Electricity Increase once off payment': ['Electricity Increase once off payment',
    'Electricity',
    'Increase',
    'once',
    'off',
    'payment',
    'electricity',
    'increase',
    'once',
    'off',
    'payment',
    'Electricity Increase once off payment']},
  {'Salaries': ['Salaries', 'Salaries', 'salary', 'Salaries']},
  {'Salaries overtime': ['Salaries overtime',
    'Salaries',
    'overtime',
    'salary',
    'overtime',
    'Salaries overtime']},
  {'Bashful Overtime': ['Bashful Overtime',
    'Bashful',
    'Overtime',
    'bashful',
    'overtime',
    'Bashful Overtime']},
  {'Payment; Bashful': ['Payment; Bashful',
    'Payment',
    ';',
    'Bashful',
    'payment',
    ';',
    'bashful',
    'Payment; Bashful']},
  {'Advertising Expense': ['Advertising Expense',
    'Advertising',
    'Expense',
    'advertising',
    'expense',
    'Advertising Expense']},
  {'Advertising expense': ['Advertising expense',
    'Advertising',
    'expense',
    'advertising',
    'expense',
    'Advertising expense']},
  {'Advertising Expenses': ['Advertising Expenses',
    'Advertising',
    'Expenses',
    'advertising',
    'expense',
    'Advertising Expenses']},
  {'Transport costs': ['Transport costs',
    'Transport',
    'costs',
    'transport',
    'cost',
    'Transport costs']},
  {'Transit Costs': ['Transit Costs',
    'Transit',
    'Costs',
    'transit',
    'cost',
    'Transit Costs']},
  {'Repairs and Maintenance': ['Repairs and Maintenance',
    'Repairs',
    'and',
    'Maintenance',
    'repair',
    'and',
    'maintenance',
    'Repairs and Maintenance']},
  {'Vehicle repairs': ['Vehicle repairs',
    'Vehicle',
    'repairs',
    'vehicle',
    'repair',
    'Vehicle repairs']},
  {'Purchase of Computer Equipment': ['Purchase of Computer Equipment',
    'Purchase',
    'of',
    'Computer',
    'Equipment',
    'purchase',
    'of',
    'computer',
    'equipment',
    'Purchase of Computer Equipment']},
  {'Purchase of computer accessories': ['Purchase of computer accessories',
    'Purchase',
    'of',
    'computer',
    'accessories',
    'purchase',
    'of',
    'computer',
    'accessory',
    'Purchase of computer accessories']},
  {'Purchase of baking Equipment': ['Purchase of baking Equipment',
    'Purchase',
    'of',
    'baking',
    'Equipment',
    'purchase',
    'of',
    'baking',
    'equipment',
    'Purchase of baking Equipment']},
  {'Scar Equipment - Maintenance': ['Scar Equipment - Maintenance',
    'Scar',
    'Equipment',
    '-',
    'Maintenance',
    'scar',
    'equipment',
    '-',
    'maintenance',
    'Scar Equipment - Maintenance']},
  {'Maintenance': ['Maintenance',
    'Maintenance',
    'maintenance',
    'Maintenance']},
  {'Computer Equipment': ['Computer Equipment',
    'Computer',
    'Equipment',
    'computer',
    'equipment',
    'Computer Equipment']},
  {'Packaging products': ['Packaging products',
    'Packaging',
    'products',
    'packaging',
    'product',
    'Packaging products']},
  {'Packaging Materials': ['Packaging Materials',
    'Packaging',
    'Materials',
    'packaging',
    'material',
    'Packaging Materials']},
  {'Grumpy Wages': ['Grumpy Wages',
    'Grumpy',
    'Wages',
    'grumpy',
    'wage',
    'Grumpy Wages']},
  {'Grumpy wages': ['Grumpy wages',
    'Grumpy',
    'wages',
    'grumpy',
    'wage',
    'Grumpy wages']},
  {'Overtime': ['Overtime', 'Overtime', 'overtime', 'Overtime']},
  {'Potato': ['Potato', 'Potato', 'potato', 'Potato']},
  {'Capitalised': ['Capitalised',
    'Capitalised',
    'capitalised',
    'Capitalised']},
  {'Computer Additions': ['Computer Additions',
    'Computer',
    'Additions',
    'computer',
    'addition',
    'Computer Additions']},
  {'Staff Party': ['Staff Party',
    'Staff',
    'Party',
    'staff',
    'party',
    'Staff Party']},
  {'Year end Party - Entertainment': ['Year end Party - Entertainment',
    'Year',
    'end',
    'Party',
    '-',
    'Entertainment',
    'year',
    'end',
    'party',
    '-',
    'entertainment',
    'Year end Party - Entertainment']},
  {'Additional Office Machine': ['Additional Office Machine',
    'Additional',
    'Office',
    'Machine',
    'additional',
    'office',
    'machine',
    'Additional Office Machine']},
  {'Consulting Fees': ['Consulting Fees',
    'Consulting',
    'Fees',
    'consulting',
    'fee',
    'Consulting Fees']},
  {'nan': ['nan', 'nan', 'nan', 'nan']}],
 'item_code': [{'nan': ['nan', 'nan', 'nan', 'nan']},
  {'TIN001': ['TIN001', 'TIN001', 'tin001', 'TIN001']},
  {'CHO001': ['CHO001', 'CHO001', 'cho001', 'CHO001']},
  {'CIN001': ['CIN001', 'CIN001', 'cin001', 'CIN001']},
  {'JAS001': ['JAS001', 'JAS001', 'jas001', 'JAS001']},
  {'FR001': ['FR001', 'FR001', 'fr001', 'FR001']},
  {'ARI001': ['ARI001', 'ARI001', 'ari001', 'ARI001']}],
 'quantity': [{'1.0': ['1.0', '1.0', '1.0', '1.0']},
  {'10.0': ['10.0', '10.0', '10.0', '10.0']},
  {'20.0': ['20.0', '20.0', '20.0', '20.0']},
  {'100.0': ['100.0', '100.0', '100.0', '100.0']},
  {'200.0': ['200.0', '200.0', '200.0', '200.0']},
  {'500.0': ['500.0', '500.0', '500.0', '500.0']},
  {'99.0': ['99.0', '99.0', '99.0', '99.0']},
  {'60.0': ['60.0', '60.0', '60.0', '60.0']},
  {'50.0': ['50.0', '50.0', '50.0', '50.0']},
  {'220.0': ['220.0', '220.0', '220.0', '220.0']},
  {'30.0': ['30.0', '30.0', '30.0', '30.0']},
  {'45.0': ['45.0', '45.0', '45.0', '45.0']},
  {'2.0': ['2.0', '2.0', '2.0', '2.0']},
  {'150.0': ['150.0', '150.0', '150.0', '150.0']},
  {'175.0': ['175.0', '175.0', '175.0', '175.0']},
  {'55.0': ['55.0', '55.0', '55.0', '55.0']},
  {'250.0': ['250.0', '250.0', '250.0', '250.0']},
  {'15.0': ['15.0', '15.0', '15.0', '15.0']},
  {'40.0': ['40.0', '40.0', '40.0', '40.0']},
  {'400.0': ['400.0', '400.0', '400.0', '400.0']},
  {'35.0': ['35.0', '35.0', '35.0', '35.0']},
  {'130.0': ['130.0', '130.0', '130.0', '130.0']},
  {'3.0': ['3.0', '3.0', '3.0', '3.0']},
  {'450.0': ['450.0', '450.0', '450.0', '450.0']},
  {'4.0': ['4.0', '4.0', '4.0', '4.0']},
  {'1400.0': ['1400.0', '1400.0', '1400.0', '1400.0']},
  {'300.0': ['300.0', '300.0', '300.0', '300.0']},
  {'1750.0': ['1750.0', '1750.0', '1750.0', '1750.0']},
  {'1000.0': ['1000.0', '1000.0', '1000.0', '1000.0']},
  {'2000.0': ['2000.0', '2000.0', '2000.0', '2000.0']},
  {'nan': ['nan', 'nan', 'nan', 'nan']}],
 'name': [{'Snow White': ['Snow White',
    'Snow',
    'White',
    'snow',
    'white',
    'Snow White']},
  {'Maleficent': ['Maleficent', 'Maleficent', 'maleficent', 'Maleficent']},
  {'Mrs Potts': ['Mrs Potts', 'Mrs', 'Potts', 'mr', 'potts', 'Mrs Potts']},
  {'Cindarella': ['Cindarella', 'Cindarella', 'cindarella', 'Cindarella']},
  {'Elsa Frozen': ['Elsa Frozen',
    'Elsa',
    'Frozen',
    'elsa',
    'frozen',
    'Elsa Frozen']},
  {'Anna Frozen 1': ['Anna Frozen 1',
    'Anna',
    'Frozen',
    '1',
    'anna',
    'frozen',
    '1',
    'Anna Frozen 1']},
  {'Ariel': ['Ariel', 'Ariel', 'ariel', 'Ariel']},
  {'Tinkerbell': ['Tinkerbell', 'Tinkerbell', 'tinkerbell', 'Tinkerbell']},
  {'Ariel new': ['Ariel new', 'Ariel', 'new', 'ariel', 'new', 'Ariel new']},
  {'Alice': ['Alice', 'Alice', 'alice', 'Alice']},
  {'Judy Hopps': ['Judy Hopps',
    'Judy',
    'Hopps',
    'judy',
    'hopps',
    'Judy Hopps']},
  {'Jasmine': ['Jasmine', 'Jasmine', 'jasmine', 'Jasmine']},
  {'Thomas Training': ['Thomas Training',
    'Thomas',
    'Training',
    'thomas',
    'training',
    'Thomas Training']},
  {'Captain Hook': ['Captain Hook',
    'Captain',
    'Hook',
    'captain',
    'hook',
    'Captain Hook']},
  {'Michelle Mitchell': ['Michelle Mitchell',
    'Michelle',
    'Mitchell',
    'michelle',
    'mitchell',
    'Michelle Mitchell']},
  {'Ele Kyriazis': ['Ele Kyriazis',
    'Ele',
    'Kyriazis',
    'ele',
    'kyriazis',
    'Ele Kyriazis']},
  {'Aladdin': ['Aladdin', 'Aladdin', 'aladdin', 'Aladdin']},
  {'Jafar Bank': ['Jafar Bank',
    'Jafar',
    'Bank',
    'jafar',
    'bank',
    'Jafar Bank']},
  {'Lumiere Electricity': ['Lumiere Electricity',
    'Lumiere',
    'Electricity',
    'lumiere',
    'electricity',
    'Lumiere Electricity']},
  {'Step Mother': ['Step Mother',
    'Step',
    'Mother',
    'step',
    'mother',
    'Step Mother']},
  {'Hans Prince': ['Hans Prince',
    'Hans',
    'Prince',
    'han',
    'prince',
    'Hans Prince']},
  {'Bashful': ['Bashful', 'Bashful', 'bashful', 'Bashful']},
  {'Ursula': ['Ursula', 'Ursula', 'ursula', 'Ursula']},
  {'Gaston Advertising': ['Gaston Advertising',
    'Gaston',
    'Advertising',
    'gaston',
    'advertising',
    'Gaston Advertising']},
  {'Sir Miles Axlerod': ['Sir Miles Axlerod',
    'Sir',
    'Miles',
    'Axlerod',
    'sir',
    'mile',
    'axlerod',
    'Sir Miles Axlerod']},
  {'Guido': ['Guido', 'Guido', 'guido', 'Guido']},
  {'Iago Cake': ['Iago Cake', 'Iago', 'Cake', 'iago', 'cake', 'Iago Cake']},
  {'Scar Enterprises': ['Scar Enterprises',
    'Scar',
    'Enterprises',
    'scar',
    'enterprise',
    'Scar Enterprises']},
  {'Claude Frollo': ['Claude Frollo',
    'Claude',
    'Frollo',
    'claude',
    'frollo',
    'Claude Frollo']},
  {'Grumpy': ['Grumpy', 'Grumpy', 'grumpy', 'Grumpy']},
  {'Potato man': ['Potato man',
    'Potato',
    'man',
    'potato',
    'man',
    'Potato man']},
  {'Dawn Bellwether': ['Dawn Bellwether',
    'Dawn',
    'Bellwether',
    'dawn',
    'bellwether',
    'Dawn Bellwether']},
  {'Shere Khan': ['Shere Khan',
    'Shere',
    'Khan',
    'shere',
    'khan',
    'Shere Khan']},
  {'Elle Elves': ['Elle Elves', 'Elle', 'Elves', 'elle', 'elf', 'Elle Elves']},
  {'Gastonia': ['Gastonia', 'Gastonia', 'gastonia', 'Gastonia']},
  {'Frozen King': ['Frozen King',
    'Frozen',
    'King',
    'frozen',
    'king',
    'Frozen King']},
  {'Anna Frozen 2': ['Anna Frozen 2',
    'Anna',
    'Frozen',
    '2',
    'anna',
    'frozen',
    '2',
    'Anna Frozen 2']},
  {'Aladdinn': ['Aladdinn', 'Aladdinn', 'aladdinn', 'Aladdinn']}],
 'email': [{'nan': ['nan', 'nan', 'nan', 'nan']},
  {'frozen@mail.com': ['frozen@mail.com',
    'frozen',
    '@',
    'mail.com',
    'frozen',
    '@',
    'mail.com',
    'frozen@mail.com']},
  {'ariel@mail.com': ['ariel@mail.com',
    'ariel',
    '@',
    'mail.com',
    'ariel',
    '@',
    'mail.com',
    'ariel@mail.com']},
  {'aladdin@disney.com': ['aladdin@disney.com',
    'aladdin',
    '@',
    'disney.com',
    'aladdin',
    '@',
    'disney.com',
    'aladdin@disney.com']},
  {'aladdinn@disney.com': ['aladdinn@disney.com',
    'aladdinn',
    '@',
    'disney.com',
    'aladdinn',
    '@',
    'disney.com',
    'aladdinn@disney.com']}],
 'phone': [{'nan': ['nan', 'nan', 'nan', 'nan']}],
 'columns': [{'paid': ['paid', 'paid', 'paid', 'paid']},
  {'currency': ['currency', 'currency', 'currency', 'currency']},
  {'is_sale': ['is_sale', 'is_sale', 'is_sale', 'is', 'sale']},
  {'description': ['description',
    'description',
    'description',
    'description']},
  {'item_code': ['item_code', 'item_code', 'item_code', 'item', 'code']},
  {'quantity': ['quantity', 'quantity', 'quantity', 'quantity']},
  {'name': ['name', 'name', 'name', 'name']},
  {'is_supplier': ['is_supplier',
    'is_supplier',
    'is_supplier',
    'is',
    'supplier']},
  {'is_customer': ['is_customer',
    'is_customer',
    'is_customer',
    'is',
    'customer']},
  {'email': ['email', 'email', 'email', 'email']},
  {'phone': ['phone', 'phone', 'phone', 'phone']}]}

In [13]:
#Removing the stop words
import nltk
from nltk.corpus import stopwords

# Download the stop words
nltk.download('stopwords')

# Get the English stop words
stop_words = set(stopwords.words('english'))

# Function to remove stop words from a list of words
def remove_stop_words(word_list):
    return [word for word in word_list if word.lower() not in stop_words]

# Removing stop words from the augmented_dict
for key, values in augmented_dict.items():
    for value_dict in values:
        for original_value, variations in value_dict.items():
            cleaned_variations = remove_stop_words(variations)
            value_dict[original_value] = cleaned_variations

[nltk_data] Downloading package stopwords to /home/sachin/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [14]:
augmented_dict

{'currency': [{'GBP': ['GBP', 'GBP', 'gbp', 'GBP']},
  {'NZD': ['NZD', 'NZD', 'nzd', 'NZD']},
  {'ZAR': ['ZAR', 'ZAR', 'zar', 'ZAR']},
  {'NGN': ['NGN', 'NGN', 'ngn', 'NGN']},
  {'INR': ['INR', 'INR', 'inr', 'INR']},
  {'nan': ['nan', 'nan', 'nan', 'nan']}],
 'description': [{'Rental income': ['Rental income',
    'Rental',
    'income',
    'rental',
    'income',
    'Rental income']},
  {'Rental Income for September': ['Rental Income for September',
    'Rental',
    'Income',
    'September',
    'rental',
    'income',
    'september',
    'Rental Income for September']},
  {'Rental Income': ['Rental Income',
    'Rental',
    'Income',
    'rental',
    'income',
    'Rental Income']},
  {'Tinkerbell cake': ['Tinkerbell cake',
    'Tinkerbell',
    'cake',
    'tinkerbell',
    'cake',
    'Tinkerbell cake']},
  {'Purchase of building': ['Purchase of building',
    'Purchase',
    'building',
    'purchase',
    'building',
    'Purchase of building']},
  {'Table': ['Table', 'Table', 'table', 'Table']},
  {'Baking Lessons': ['Baking Lessons',
    'Baking',
    'Lessons',
    'baking',
    'lesson',
    'Baking Lessons']},
  {'Zoo Chocolates StoredProviderCaching': ['Zoo Chocolates StoredProviderCaching',
    'Zoo',
    'Chocolates',
    'StoredProviderCaching',
    'zoo',
    'chocolate',
    'storedprovidercaching',
    'Zoo Chocolates StoredProviderCaching']},
  {'Zoo Chocolates': ['Zoo Chocolates',
    'Zoo',
    'Chocolates',
    'zoo',
    'chocolate',
    'Zoo Chocolates']},
  {'Cinderella Cupcakes': ['Cinderella Cupcakes',
    'Cinderella',
    'Cupcakes',
    'cinderella',
    'cupcake',
    'Cinderella Cupcakes']},
  {'Jasmine Cake': ['Jasmine Cake',
    'Jasmine',
    'Cake',
    'jasmine',
    'cake',
    'Jasmine Cake']},
  {'Frozen cupcakes': ['Frozen cupcakes',
    'Frozen',
    'cupcakes',
    'frozen',
    'cupcake',
    'Frozen cupcakes']},
  {'Ariel Cupcakes': ['Ariel Cupcakes',
    'Ariel',
    'Cupcakes',
    'ariel',
    'cupcake',
    'Ariel Cupcakes']},
  {'Training': ['Training', 'Training', 'training', 'Training']},
  {'Bank Charges': ['Bank Charges',
    'Bank',
    'Charges',
    'bank',
    'charge',
    'Bank Charges']},
  {'Interest expense': ['Interest expense',
    'Interest',
    'expense',
    'interest',
    'expense',
    'Interest expense']},
  {'Electricity': ['Electricity',
    'Electricity',
    'electricity',
    'Electricity']},
  {'Electricity Increase once off payment': ['Electricity Increase once off payment',
    'Electricity',
    'Increase',
    'payment',
    'electricity',
    'increase',
    'payment',
    'Electricity Increase once off payment']},
  {'Salaries': ['Salaries', 'Salaries', 'salary', 'Salaries']},
  {'Salaries overtime': ['Salaries overtime',
    'Salaries',
    'overtime',
    'salary',
    'overtime',
    'Salaries overtime']},
  {'Bashful Overtime': ['Bashful Overtime',
    'Bashful',
    'Overtime',
    'bashful',
    'overtime',
    'Bashful Overtime']},
  {'Payment; Bashful': ['Payment; Bashful',
    'Payment',
    ';',
    'Bashful',
    'payment',
    ';',
    'bashful',
    'Payment; Bashful']},
  {'Advertising Expense': ['Advertising Expense',
    'Advertising',
    'Expense',
    'advertising',
    'expense',
    'Advertising Expense']},
  {'Advertising expense': ['Advertising expense',
    'Advertising',
    'expense',
    'advertising',
    'expense',
    'Advertising expense']},
  {'Advertising Expenses': ['Advertising Expenses',
    'Advertising',
    'Expenses',
    'advertising',
    'expense',
    'Advertising Expenses']},
  {'Transport costs': ['Transport costs',
    'Transport',
    'costs',
    'transport',
    'cost',
    'Transport costs']},
  {'Transit Costs': ['Transit Costs',
    'Transit',
    'Costs',
    'transit',
    'cost',
    'Transit Costs']},
  {'Repairs and Maintenance': ['Repairs and Maintenance',
    'Repairs',
    'Maintenance',
    'repair',
    'maintenance',
    'Repairs and Maintenance']},
  {'Vehicle repairs': ['Vehicle repairs',
    'Vehicle',
    'repairs',
    'vehicle',
    'repair',
    'Vehicle repairs']},
  {'Purchase of Computer Equipment': ['Purchase of Computer Equipment',
    'Purchase',
    'Computer',
    'Equipment',
    'purchase',
    'computer',
    'equipment',
    'Purchase of Computer Equipment']},
  {'Purchase of computer accessories': ['Purchase of computer accessories',
    'Purchase',
    'computer',
    'accessories',
    'purchase',
    'computer',
    'accessory',
    'Purchase of computer accessories']},
  {'Purchase of baking Equipment': ['Purchase of baking Equipment',
    'Purchase',
    'baking',
    'Equipment',
    'purchase',
    'baking',
    'equipment',
    'Purchase of baking Equipment']},
  {'Scar Equipment - Maintenance': ['Scar Equipment - Maintenance',
    'Scar',
    'Equipment',
    '-',
    'Maintenance',
    'scar',
    'equipment',
    '-',
    'maintenance',
    'Scar Equipment - Maintenance']},
  {'Maintenance': ['Maintenance',
    'Maintenance',
    'maintenance',
    'Maintenance']},
  {'Computer Equipment': ['Computer Equipment',
    'Computer',
    'Equipment',
    'computer',
    'equipment',
    'Computer Equipment']},
  {'Packaging products': ['Packaging products',
    'Packaging',
    'products',
    'packaging',
    'product',
    'Packaging products']},
  {'Packaging Materials': ['Packaging Materials',
    'Packaging',
    'Materials',
    'packaging',
    'material',
    'Packaging Materials']},
  {'Grumpy Wages': ['Grumpy Wages',
    'Grumpy',
    'Wages',
    'grumpy',
    'wage',
    'Grumpy Wages']},
  {'Grumpy wages': ['Grumpy wages',
    'Grumpy',
    'wages',
    'grumpy',
    'wage',
    'Grumpy wages']},
  {'Overtime': ['Overtime', 'Overtime', 'overtime', 'Overtime']},
  {'Potato': ['Potato', 'Potato', 'potato', 'Potato']},
  {'Capitalised': ['Capitalised',
    'Capitalised',
    'capitalised',
    'Capitalised']},
  {'Computer Additions': ['Computer Additions',
    'Computer',
    'Additions',
    'computer',
    'addition',
    'Computer Additions']},
  {'Staff Party': ['Staff Party',
    'Staff',
    'Party',
    'staff',
    'party',
    'Staff Party']},
  {'Year end Party - Entertainment': ['Year end Party - Entertainment',
    'Year',
    'end',
    'Party',
    '-',
    'Entertainment',
    'year',
    'end',
    'party',
    '-',
    'entertainment',
    'Year end Party - Entertainment']},
  {'Additional Office Machine': ['Additional Office Machine',
    'Additional',
    'Office',
    'Machine',
    'additional',
    'office',
    'machine',
    'Additional Office Machine']},
  {'Consulting Fees': ['Consulting Fees',
    'Consulting',
    'Fees',
    'consulting',
    'fee',
    'Consulting Fees']},
  {'nan': ['nan', 'nan', 'nan', 'nan']}],
 'item_code': [{'nan': ['nan', 'nan', 'nan', 'nan']},
  {'TIN001': ['TIN001', 'TIN001', 'tin001', 'TIN001']},
  {'CHO001': ['CHO001', 'CHO001', 'cho001', 'CHO001']},
  {'CIN001': ['CIN001', 'CIN001', 'cin001', 'CIN001']},
  {'JAS001': ['JAS001', 'JAS001', 'jas001', 'JAS001']},
  {'FR001': ['FR001', 'FR001', 'fr001', 'FR001']},
  {'ARI001': ['ARI001', 'ARI001', 'ari001', 'ARI001']}],
 'quantity': [{'1.0': ['1.0', '1.0', '1.0', '1.0']},
  {'10.0': ['10.0', '10.0', '10.0', '10.0']},
  {'20.0': ['20.0', '20.0', '20.0', '20.0']},
  {'100.0': ['100.0', '100.0', '100.0', '100.0']},
  {'200.0': ['200.0', '200.0', '200.0', '200.0']},
  {'500.0': ['500.0', '500.0', '500.0', '500.0']},
  {'99.0': ['99.0', '99.0', '99.0', '99.0']},
  {'60.0': ['60.0', '60.0', '60.0', '60.0']},
  {'50.0': ['50.0', '50.0', '50.0', '50.0']},
  {'220.0': ['220.0', '220.0', '220.0', '220.0']},
  {'30.0': ['30.0', '30.0', '30.0', '30.0']},
  {'45.0': ['45.0', '45.0', '45.0', '45.0']},
  {'2.0': ['2.0', '2.0', '2.0', '2.0']},
  {'150.0': ['150.0', '150.0', '150.0', '150.0']},
  {'175.0': ['175.0', '175.0', '175.0', '175.0']},
  {'55.0': ['55.0', '55.0', '55.0', '55.0']},
  {'250.0': ['250.0', '250.0', '250.0', '250.0']},
  {'15.0': ['15.0', '15.0', '15.0', '15.0']},
  {'40.0': ['40.0', '40.0', '40.0', '40.0']},
  {'400.0': ['400.0', '400.0', '400.0', '400.0']},
  {'35.0': ['35.0', '35.0', '35.0', '35.0']},
  {'130.0': ['130.0', '130.0', '130.0', '130.0']},
  {'3.0': ['3.0', '3.0', '3.0', '3.0']},
  {'450.0': ['450.0', '450.0', '450.0', '450.0']},
  {'4.0': ['4.0', '4.0', '4.0', '4.0']},
  {'1400.0': ['1400.0', '1400.0', '1400.0', '1400.0']},
  {'300.0': ['300.0', '300.0', '300.0', '300.0']},
  {'1750.0': ['1750.0', '1750.0', '1750.0', '1750.0']},
  {'1000.0': ['1000.0', '1000.0', '1000.0', '1000.0']},
  {'2000.0': ['2000.0', '2000.0', '2000.0', '2000.0']},
  {'nan': ['nan', 'nan', 'nan', 'nan']}],
 'name': [{'Snow White': ['Snow White',
    'Snow',
    'White',
    'snow',
    'white',
    'Snow White']},
  {'Maleficent': ['Maleficent', 'Maleficent', 'maleficent', 'Maleficent']},
  {'Mrs Potts': ['Mrs Potts', 'Mrs', 'Potts', 'mr', 'potts', 'Mrs Potts']},
  {'Cindarella': ['Cindarella', 'Cindarella', 'cindarella', 'Cindarella']},
  {'Elsa Frozen': ['Elsa Frozen',
    'Elsa',
    'Frozen',
    'elsa',
    'frozen',
    'Elsa Frozen']},
  {'Anna Frozen 1': ['Anna Frozen 1',
    'Anna',
    'Frozen',
    '1',
    'anna',
    'frozen',
    '1',
    'Anna Frozen 1']},
  {'Ariel': ['Ariel', 'Ariel', 'ariel', 'Ariel']},
  {'Tinkerbell': ['Tinkerbell', 'Tinkerbell', 'tinkerbell', 'Tinkerbell']},
  {'Ariel new': ['Ariel new', 'Ariel', 'new', 'ariel', 'new', 'Ariel new']},
  {'Alice': ['Alice', 'Alice', 'alice', 'Alice']},
  {'Judy Hopps': ['Judy Hopps',
    'Judy',
    'Hopps',
    'judy',
    'hopps',
    'Judy Hopps']},
  {'Jasmine': ['Jasmine', 'Jasmine', 'jasmine', 'Jasmine']},
  {'Thomas Training': ['Thomas Training',
    'Thomas',
    'Training',
    'thomas',
    'training',
    'Thomas Training']},
  {'Captain Hook': ['Captain Hook',
    'Captain',
    'Hook',
    'captain',
    'hook',
    'Captain Hook']},
  {'Michelle Mitchell': ['Michelle Mitchell',
    'Michelle',
    'Mitchell',
    'michelle',
    'mitchell',
    'Michelle Mitchell']},
  {'Ele Kyriazis': ['Ele Kyriazis',
    'Ele',
    'Kyriazis',
    'ele',
    'kyriazis',
    'Ele Kyriazis']},
  {'Aladdin': ['Aladdin', 'Aladdin', 'aladdin', 'Aladdin']},
  {'Jafar Bank': ['Jafar Bank',
    'Jafar',
    'Bank',
    'jafar',
    'bank',
    'Jafar Bank']},
  {'Lumiere Electricity': ['Lumiere Electricity',
    'Lumiere',
    'Electricity',
    'lumiere',
    'electricity',
    'Lumiere Electricity']},
  {'Step Mother': ['Step Mother',
    'Step',
    'Mother',
    'step',
    'mother',
    'Step Mother']},
  {'Hans Prince': ['Hans Prince',
    'Hans',
    'Prince',
    'han',
    'prince',
    'Hans Prince']},
  {'Bashful': ['Bashful', 'Bashful', 'bashful', 'Bashful']},
  {'Ursula': ['Ursula', 'Ursula', 'ursula', 'Ursula']},
  {'Gaston Advertising': ['Gaston Advertising',
    'Gaston',
    'Advertising',
    'gaston',
    'advertising',
    'Gaston Advertising']},
  {'Sir Miles Axlerod': ['Sir Miles Axlerod',
    'Sir',
    'Miles',
    'Axlerod',
    'sir',
    'mile',
    'axlerod',
    'Sir Miles Axlerod']},
  {'Guido': ['Guido', 'Guido', 'guido', 'Guido']},
  {'Iago Cake': ['Iago Cake', 'Iago', 'Cake', 'iago', 'cake', 'Iago Cake']},
  {'Scar Enterprises': ['Scar Enterprises',
    'Scar',
    'Enterprises',
    'scar',
    'enterprise',
    'Scar Enterprises']},
  {'Claude Frollo': ['Claude Frollo',
    'Claude',
    'Frollo',
    'claude',
    'frollo',
    'Claude Frollo']},
  {'Grumpy': ['Grumpy', 'Grumpy', 'grumpy', 'Grumpy']},
  {'Potato man': ['Potato man',
    'Potato',
    'man',
    'potato',
    'man',
    'Potato man']},
  {'Dawn Bellwether': ['Dawn Bellwether',
    'Dawn',
    'Bellwether',
    'dawn',
    'bellwether',
    'Dawn Bellwether']},
  {'Shere Khan': ['Shere Khan',
    'Shere',
    'Khan',
    'shere',
    'khan',
    'Shere Khan']},
  {'Elle Elves': ['Elle Elves', 'Elle', 'Elves', 'elle', 'elf', 'Elle Elves']},
  {'Gastonia': ['Gastonia', 'Gastonia', 'gastonia', 'Gastonia']},
  {'Frozen King': ['Frozen King',
    'Frozen',
    'King',
    'frozen',
    'king',
    'Frozen King']},
  {'Anna Frozen 2': ['Anna Frozen 2',
    'Anna',
    'Frozen',
    '2',
    'anna',
    'frozen',
    '2',
    'Anna Frozen 2']},
  {'Aladdinn': ['Aladdinn', 'Aladdinn', 'aladdinn', 'Aladdinn']}],
 'email': [{'nan': ['nan', 'nan', 'nan', 'nan']},
  {'frozen@mail.com': ['frozen@mail.com',
    'frozen',
    '@',
    'mail.com',
    'frozen',
    '@',
    'mail.com',
    'frozen@mail.com']},
  {'ariel@mail.com': ['ariel@mail.com',
    'ariel',
    '@',
    'mail.com',
    'ariel',
    '@',
    'mail.com',
    'ariel@mail.com']},
  {'aladdin@disney.com': ['aladdin@disney.com',
    'aladdin',
    '@',
    'disney.com',
    'aladdin',
    '@',
    'disney.com',
    'aladdin@disney.com']},
  {'aladdinn@disney.com': ['aladdinn@disney.com',
    'aladdinn',
    '@',
    'disney.com',
    'aladdinn',
    '@',
    'disney.com',
    'aladdinn@disney.com']}],
 'phone': [{'nan': ['nan', 'nan', 'nan', 'nan']}],
 'columns': [{'paid': ['paid', 'paid', 'paid', 'paid']},
  {'currency': ['currency', 'currency', 'currency', 'currency']},
  {'is_sale': ['is_sale', 'is_sale', 'is_sale', 'sale']},
  {'description': ['description',
    'description',
    'description',
    'description']},
  {'item_code': ['item_code', 'item_code', 'item_code', 'item', 'code']},
  {'quantity': ['quantity', 'quantity', 'quantity', 'quantity']},
  {'name': ['name', 'name', 'name', 'name']},
  {'is_supplier': ['is_supplier', 'is_supplier', 'is_supplier', 'supplier']},
  {'is_customer': ['is_customer', 'is_customer', 'is_customer', 'customer']},
  {'email': ['email', 'email', 'email', 'email']},
  {'phone': ['phone', 'phone', 'phone', 'phone']}]}

In [15]:
import pickle

with open('./data/augmented_dict.pkl', 'wb') as f:
    pickle.dump(augmented_dict, f)

In [16]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer, PorterStemmer
from collections import Counter

# Initialize the WordNetLemmatizer and PorterStemmer
wnl = WordNetLemmatizer()
ps = PorterStemmer()

# Function to tokenize, stem, and lemmatize a string
def process_text(text):
    tokens = word_tokenize(text)
    lemmatized_tokens = [wnl.lemmatize(token.lower()) for token in tokens]
    stemmed_tokens = [ps.stem(token.lower()) for token in tokens]
    return tokens, lemmatized_tokens, stemmed_tokens

# Function to search for matches in an augmented dictionary
def search_in_augmented_dict(augmented_dict, input_string):
    original, lemmatized, stemmed = process_text(input_string)
    search_tokens = original + lemmatized + stemmed
    
    results = []
    
    for key, values in augmented_dict.items():
        matches_counter = Counter()
        for value_dict in values:
            for original_value, variations in value_dict.items():
                for variation in variations:
                    if variation.lower() in search_tokens:
                        matches_counter[original_value] += 1
        
        if matches_counter:
            results.append({key: dict(matches_counter)})
    
    return results

In [39]:
result = search_in_augmented_dict(augmented_dict, "Give me a list of all my suppliers")

In [40]:
result

[{'columns': {'is_supplier': 1}}]

In [19]:
merged.head()

,paid,currency,is_sale,description,item_code,quantity,name,is_supplier,is_customer,email,phone
0,True,GBP,True,Rental income,NaN,1.0,Snow White,False,True,NaN,NaN
1,True,GBP,True,Rental income,NaN,1.0,Snow White,False,True,NaN,NaN
2,True,GBP,True,Rental income,NaN,1.0,Snow White,False,True,NaN,NaN
3,True,GBP,True,Rental income,NaN,1.0,Snow White,False,True,NaN,NaN
4,True,GBP,True,Rental income,NaN,1.0,Snow White,False,True,NaN,NaN

In [35]:
search_in_augmented_dict(augmented_dict, "rental and electricity")

[{'description': {'Rental income': 2,
   'Rental Income for September': 2,
   'Rental Income': 2,
   'Electricity': 4,
   'Electricity Increase once off payment': 2}},
 {'name': {'Lumiere Electricity': 2}}]

In [21]:
import pandas as pd
merged2 = pd.read_csv("./data/merged.csv")

In [22]:
merged2.head()

,Unnamed: 0,id_invoice,issue_date,due_date,paid_date,paid,contact_id,total,amount_due,exchange_rate,...,id_invoice_info,description,item_code,quantity,id,name,is_supplier,is_customer,email,phone
0,0,90381d5a-9348-4208-915c-60b082378370,2021-01-31T00:00:00.000Z,2021-02-06T00:00:00.000Z,2021-02-06T00:00:00.000Z,True,8e81fbc4-4f33-4ae9-bf5e-a2415372e77b,174.8,0.0,1.0,...,a90834f9-90b5-4342-9cb6-f8d45b35fd7e,Rental income,NaN,1.0,8e81fbc4-4f33-4ae9-bf5e-a2415372e77b,Snow White,False,True,NaN,NaN
1,1,3dec381c-7af5-436d-8b35-2d3a69b95f89,2021-02-28T00:00:00.000Z,2021-03-06T00:00:00.000Z,2021-03-06T00:00:00.000Z,True,8e81fbc4-4f33-4ae9-bf5e-a2415372e77b,174.8,0.0,1.0,...,3554bf7d-bd10-449c-b05a-5a5e478bab73,Rental income,NaN,1.0,8e81fbc4-4f33-4ae9-bf5e-a2415372e77b,Snow White,False,True,NaN,NaN
2,2,0222b396-f017-4a90-ad5b-4a8e241d4afc,2021-03-31T00:00:00.000Z,2021-04-06T00:00:00.000Z,2021-04-06T00:00:00.000Z,True,8e81fbc4-4f33-4ae9-bf5e-a2415372e77b,174.8,0.0,1.0,...,1e35c6e6-456d-4dae-9d7f-c4ee6b15c06e,Rental income,NaN,1.0,8e81fbc4-4f33-4ae9-bf5e-a2415372e77b,Snow White,False,True,NaN,NaN
3,3,eb59789d-a21e-4628-a774-17a3bf38607b,2021-04-30T00:00:00.000Z,2021-05-06T00:00:00.000Z,2021-05-06T00:00:00.000Z,True,8e81fbc4-4f33-4ae9-bf5e-a2415372e77b,174.8,0.0,1.0,...,debf819e-83f7-41bf-9cef-1389fe2b5d94,Rental income,NaN,1.0,8e81fbc4-4f33-4ae9-bf5e-a2415372e77b,Snow White,False,True,NaN,NaN
4,4,87d4c9dc-f37a-43a2-8aab-40ba13f3a8ac,2021-05-31T00:00:00.000Z,2021-06-06T00:00:00.000Z,2021-06-06T00:00:00.000Z,True,8e81fbc4-4f33-4ae9-bf5e-a2415372e77b,174.8,0.0,1.0,...,f0e212e7-de75-4270-826f-50d5a75ce268,Rental income,NaN,1.0,8e81fbc4-4f33-4ae9-bf5e-a2415372e77b,Snow White,False,True,NaN,NaN

In [41]:
import pandas as pd

def filter_dataframe(df, conditions):
    # Initialize a list to hold temporary DataFrames for each condition
    temp_dfs = []
    
    # Loop through each condition dictionary
    for condition in conditions:
        for key, sub_dict in condition.items():
            # Initialize a list to hold filtered DataFrames for each value in a single column
            temp_dfs_single_column = []

            # Special handling for 'columns' key, especially for 'is_' columns
            if key == 'columns':
                for column, frequency in sub_dict.items():
                    if column.startswith('is_'):
                        temp_df = df[df[column] == True]
                        if not temp_df.empty:
                            temp_dfs_single_column.append(temp_df)
            else:
                # General case: filter using given column value and frequency
                for column_value, frequency in sub_dict.items():
                    temp_df = df[df[key] == column_value]
                    if not temp_df.empty:
                        temp_dfs_single_column.append(temp_df)
                        
            # Combine the rows that satisfy any of the conditions within a single column
            if temp_dfs_single_column:
                combined_df_single_column = pd.concat(temp_dfs_single_column).drop_duplicates()
                temp_dfs.append(combined_df_single_column)

    # Combine all the conditions into one DataFrame and drop duplicate rows
    if temp_dfs:
        filtered_df = pd.concat(temp_dfs).drop_duplicates()
        return filtered_df
    else:
        print("No matching records found.")
        return pd.DataFrame()


result = filter_dataframe(merged2,[{'columns': {'is_supplier': 1}}])

KeyError: 'columns'

In [37]:
result.shape

(37, 23)

In [38]:
result

,Unnamed: 0,id_invoice,issue_date,due_date,paid_date,paid,contact_id,total,amount_due,exchange_rate,...,id_invoice_info,description,item_code,quantity,id,name,is_supplier,is_customer,email,phone
0,241,b887446c-8d9e-4f7a-9e9f-3e5948160161,2021-03-05T00:00:00.000Z,2021-03-30T00:00:00.000Z,2022-03-30T00:00:00.000Z,True,89ea79cb-a445-4720-8368-b0887f4157bb,135.137676,0.0,21.2746,...,6d267bc4-1a91-4f84-9cce-64f3bd2ddcb8,Electricity,NaN,1.0,89ea79cb-a445-4720-8368-b0887f4157bb,Lumiere Electricity,True,False,NaN,NaN
1,242,fe667a27-99fe-4441-83cd-a4fc230a1ea1,2021-04-05T00:00:00.000Z,2021-04-30T00:00:00.000Z,2022-04-30T00:00:00.000Z,True,89ea79cb-a445-4720-8368-b0887f4157bb,142.072830,0.0,20.2361,...,ec5e38a1-148d-4b1f-9597-35557cc4cbad,Electricity,NaN,1.0,89ea79cb-a445-4720-8368-b0887f4157bb,Lumiere Electricity,True,False,NaN,NaN
2,243,cf255b16-f9da-4252-9fe2-e7c17f6ab9f0,2021-05-05T00:00:00.000Z,2021-05-30T00:00:00.000Z,NaN,False,89ea79cb-a445-4720-8368-b0887f4157bb,143.952253,0.0,19.9719,...,a3ca61d5-9a3d-4a61-a242-9501527472c6,Electricity,NaN,1.0,89ea79cb-a445-4720-8368-b0887f4157bb,Lumiere Electricity,True,False,NaN,NaN
3,244,d7998033-6dd6-406b-aa21-979d62229046,2021-06-05T00:00:00.000Z,2021-06-30T00:00:00.000Z,2021-06-30T00:00:00.000Z,True,89ea79cb-a445-4720-8368-b0887f4157bb,151.252104,0.0,19.0080,...,9658b17b-75fc-431e-9474-da1e8a6b5f0d,Electricity,NaN,1.0,89ea79cb-a445-4720-8368-b0887f4157bb,Lumiere Electricity,True,False,NaN,NaN
4,245,9508cb8b-85dd-4cd0-ace5-67d13b3d09ff,2021-07-05T00:00:00.000Z,2021-07-30T00:00:00.000Z,2021-07-30T00:00:00.000Z,True,89ea79cb-a445-4720-8368-b0887f4157bb,145.580677,0.0,19.7485,...,b7e76f79-331c-41e4-8c61-326080ef2e8b,Electricity,NaN,1.0,89ea79cb-a445-4720-8368-b0887f4157bb,Lumiere Electricity,True,False,NaN,NaN
5,246,eeca4ee8-5ae8-4046-8b86-1ffbef91252d,2021-08-05T00:00:00.000Z,2021-08-30T00:00:00.000Z,2021-08-30T00:00:00.000Z,True,89ea79cb-a445-4720-8368-b0887f4157bb,142.135343,0.0,20.2272,...,e0d9b3be-de31-4640-a2bd-7cd50c79e01f,Electricity,NaN,1.0,89ea79cb-a445-4720-8368-b0887f4157bb,Lumiere Electricity,True,False,NaN,NaN
6,247,a1e73e0e-bd6d-4751-8433-ec2c817b7ea9,2021-09-05T00:00:00.000Z,2021-09-30T00:00:00.000Z,2021-09-30T00:00:00.000Z,True,89ea79cb-a445-4720-8368-b0887f4157bb,145.105283,0.0,19.8132,...,5509d148-df58-4e2f-a02a-72c101c79b97,Electricity,NaN,1.0,89ea79cb-a445-4720-8368-b0887f4157bb,Lumiere Electricity,True,False,NaN,NaN
7,248,ca4c03a4-039d-4610-b39f-e73aa6d295d1,2021-10-05T00:00:00.000Z,2021-10-30T00:00:00.000Z,2021-11-30T00:00:00.000Z,True,89ea79cb-a445-4720-8368-b0887f4157bb,140.484439,0.0,20.4649,...,0c280890-19cf-4436-8180-e509ac11f7d6,Electricity,NaN,1.0,89ea79cb-a445-4720-8368-b0887f4157bb,Lumiere Electricity,True,False,NaN,NaN
8,249,56b8e752-d3a4-43d5-9a80-f4586af30c17,2021-11-05T00:00:00.000Z,2021-11-30T00:00:00.000Z,NaN,False,89ea79cb-a445-4720-8368-b0887f4157bb,141.626313,0.0,20.2999,...,d3f814dc-a38d-49a5-8fbc-f6e16e72feee,Electricity,NaN,1.0,89ea79cb-a445-4720-8368-b0887f4157bb,Lumiere Electricity,True,False,NaN,NaN
9,250,476d2bf5-253f-4896-809b-8224cf80d4e6,2021-11-05T00:00:00.000Z,2021-11-30T00:00:00.000Z,2021-11-30T00:00:00.000Z,True,89ea79cb-a445-4720-8368-b0887f4157bb,250.000000,0.0,1.0000,...,c416820f-7dc3-42d4-9ee2-32d55b146a67,Electricity,NaN,1.0,89ea79cb-a445-4720-8368-b0887f4157bb,Lumiere Electricity,True,False,NaN,NaN
10,251,a9adea4f-d66f-4ea4-a06a-4fddd1bb64b2,2021-12-05T00:00:00.000Z,2021-12-30T00:00:00.000Z,NaN,False,89ea79cb-a445-4720-8368-b0887f4157bb,134.937882,0.0,21.3061,...,31047417-ed7a-4b62-8462-cca0a2b26897,Electricity,NaN,1.0,89ea79cb-a445-4720-8368-b0887f4157bb,Lumiere Electricity,True,False,NaN,NaN
11,252,7fd078cf-bdc3-4037-b836-6cb0196282cd,2021-12-05T00:00:00.000Z,2021-12-30T00:00:00.000Z,2021-12-30T00:00:00.000Z,True,89ea79cb-a445-4720-8368-b0887f4157bb,250.000000,0.0,1.0000,...,9b8b761f-dc3f-4dbf-9a9e-ee84f27d5ea1,Electricity,NaN,1.0,89ea79cb-a445-4720-8368-b0887f4157bb,Lumiere Electricity,True,False,NaN,NaN
12,254,dbdb7623-8ea9-4bc6-a265-0214ea13d885,2022-01-05T00:00:00.000Z,2022-01-30T00:00:00.000Z,NaN,False,89ea79cb-a445-4720-8368-b0887f4157bb,133.392722,0.0,21.5529,...,75e557b4-bbbc-4fca-b913-a597f487583d,Electricity,NaN,1.0,89ea79cb-a445-4720-8368-b0887f4157bb,Lumiere Electricity,True,False,NaN,NaN
13,255,cda8da57-33e3-4c92-bcaa-2f6cebd99381,2022-01-05T00:00:00.000Z,2022-01-30T00:00:00.000Z,2022-01-30T00:00:00.000Z,True,89ea79cb-a445-4720-8368-b0887f4157bb,250.000000,0.0,1.0000,...,f45ed16a-f97a-4e4f-9b31-72f09d6544da,Electricity,NaN,1.0,89ea79cb-a445-4720-8368-b0887f4157bb,Lumiere Electricity,True,False,NaN,NaN
14,256,0b2629b7-95a4-4104-a94a-b8616ce4f951,2022-02-05T00:00:00.000Z,2022-02-28T00:00:00.000Z,NaN,False,89ea79cb-a445-4720-8368-b0887f4157bb,137.358700,0.0,20.9306,...,f609554c-36bf-4590-8501-11d11c7bf4d9,Electricity,NaN,1.0,89ea79cb-a445-4720-8368-b0887f4157bb,Lumiere Electricity,True,False,NaN,NaN
15,257,3f49dc63-4b59-48fd-8259-0c7075ec2dae,2022-02-05T00:00:00.000Z,2022-02-28T00:00:00.000Z,2022-02-28T00:00:00.000Z,True,89ea79cb-a445-4720-8368-b0887f4157bb,250.000000,0.0,1.0000,...,8ec89f86-1651-4f1b-b4f0-92e68801ce22,Electricity,NaN,1.0,89ea79cb-a445-4720-8368-b0887f4157bb,Lumiere Electricity,True,False,NaN,NaN
16,258,7bb8d340-4824-4b9d-9caf-9e0b634d4a93,2022-03-05T00:00:00.000Z,2022-03-30T00:00:00.000Z,NaN,False,89ea79cb-a445-4720-8368-b0887f4157bb,141.582374,0.0,20.3062,...,b058fec4-5ff6-4ea0-b18a-584a7a685150,Electricity,NaN,1.0,89ea79cb-a445-4720-8368-b0887f4157bb,Lumiere Electricity,True,False,NaN,NaN
17,259,8dc8179a-e493-4bbf-9940-00aee339adf7,2022-03-05T00:00:00.000Z,2022-03-30T00:00:00.000Z,2022-03-30T00:00:00.000Z,True,89ea79cb-a445-4720-8368-b0887f4157bb,250.000000,0.0,1.0000,...,5c87db89-be18-49fa-ae85-5dab53f1e8ac,Electricity,NaN,1.0,89ea79cb-a445-4720-8368-b0887f4157bb,Lumiere Electricity,True,False,NaN,NaN
18,260,8916b776-94fd-4715-bf47-92a72fce5c15,2022-04-05T00:00:00.000Z,2022-04-30T00:00:00.000Z,NaN,False,89ea79cb-a445-4720-8368-b0887f4157bb,150.303220,0.0,19.1280,...,b1d0503a-6969-44c3-8d45-7b8186cc5d18,Electricity,NaN,1.0,89ea79cb-a445-4720-8368-b0887f4157bb,Lumiere Electricity,True,False,NaN,NaN
19,261,ff40e46d-7330-42c0-a24c-33da9554ea7a,2022-04-05T00:00:00.000Z,2022-04-30T00:00:00.000Z,2022-04-30T00:00:00.000Z,True,89ea79cb-a445-4720-8368-b0887f4157bb,250.000000,0.0,1.0000,...,e65020bf-a116-4c16-a3d1-59b4063af7d2,Electricity,NaN,1.0,89ea79cb-a445-4720-8368-b0887f4157bb,Lumiere Electricity,True,False,NaN,NaN
20,262,b4499f4e-99ba-4bb2-9d56-9023bd590d71,2022-05-05T00:00:00.000Z,2022-05-30T00:00:00.000Z,2022-05-30T00:00:00.000Z,True,89ea79cb-a445-4720-8368-b0887f4157bb,250.000000,0.0,1.0000,...,7016950a-fa8b-40b4-9c52-4a5b9c73ebc2,Electricity,NaN,1.0,89ea79cb-a445-4720-8368-b0887f4157bb,Lumiere Electricity,True,False,NaN,NaN
21,263,3b2acc0c-fbd5-4e81-a576-ceee39a0c5ef,2022-06-05T00:00:00.000Z,2022-06-30T00:00:00.000Z,2022-06-30T00:00:00.000Z,True,89ea79cb-a445-4720-8368-b0887f4157bb,250.000000,0.0,1.0000,...,2e24b350-6b5c-4c3e-8621-6a0eb741d4a5,Electricity,NaN,1.0,89ea79cb-a445-4720-8368-b0887f4157bb,Lumiere Electricity,True,False,NaN,NaN
22,264,b2ac67e9-6c3d-4e00-9540-3a8e0b7b5eb2,2022-07-05T00:00:00.000Z,2022-07-30T00:00:00.000Z,2022-08-30T00:00:00.000Z,True,89ea79cb-a445-4720-8368-b0887f4157bb,250.000000,0.0,1.0000,...,0b3c02be-2f95-4bb0-8f44-cb4c7fb59101,Electricity,NaN,1.0,89ea79cb-a445-4720-8368-b0887f4157bb,Lumiere Electricity,True,False,NaN,NaN
23,265,30d0884d-8ce8-4bca-9b31-eb1420f08837,2022-08-05T00:00:00.000Z,2022-08-30T00:00:00.000Z,2022-08-05T00:00:00.000Z,True,89ea79cb-a445-4720-8368-b0887f4157bb,250.000000,0.0,1.0000,...,92fa8d47-cf2f-4ef6-be2a-446d14e10bbf,Electricity,NaN,1.0,89ea79cb-a445-4720-8368-b0887f4157bb,Lumiere Electricity,True,False,NaN,NaN
24,266,56b4901b-9314-4657-82f7-80f2e1099cfb,2022-09-05T00:00:00.000Z,2022-09-30T00:00:00.000Z,2022-09-30T00:00:00.000Z,True,89ea79cb-a445-4720-8368-b0887f4157bb,250.000000,0.0,1.0000,...,8df66601-76c3-413d-a711-933f892c1543,Electricity,NaN,1.0,89ea79cb-a445-4720-8368-b0887f4157bb,Lumiere Electricity,True,False,NaN,NaN
25,267,e43f546b-30ba-4f8d-9393-caf968826374,2022-10-05T00:00:00.000Z,2022-10-30T00:00:00.000Z,2022-10-30T00:00:00.000Z,True,89ea79cb-a445-4720-8368-b0887f4157bb,250.000000,0.0,1.0000,...,b3915ea7-c073-4ac2-be01-9a7ebce28a81,Electricity,NaN,1.0,89ea79cb-a445-4720-8368-b0887f4157bb,Lumiere Electricity,True,False,NaN,NaN
26,268,3868ae29-3fe0-4afb-8621-a1d2e03cf03a,2022-11-05T00:00:00.000Z,2022-11-30T00:00:00.000Z,2022-11-05T00:00:00.000Z,True,89ea79cb-a445-4720-8368-b0887f4157bb,250.000000,0.0,1.0000,...,294a3eb4-a4d4-4cdb-a795-4b63d264d1f5,Electricity,NaN,1.0,89ea79cb-a445-4720-8368-b0887f4157bb,Lumiere Electricity,True,False,NaN,NaN
27,269,453a0b3c-5eb3-4772-8177-f31d1c810994,2022-12-05T00:00:00.000Z,2022-12-30T00:00:00.000Z,2023-01-17T00:00:00.000Z,True,89ea79cb-a445-4720-8368-b0887f4157bb,250.000000,0.0,1.0000,...,e725b308-ca99-4d1f-a1c6-ec0c2e8bbd9e,Electricity,NaN,1.0,89ea79cb-a445-4720-8368-b0887f4157bb,Lumiere Electricity,True,False,NaN,NaN
28,270,f69d0678-b5be-4e10-8ef0-928e17ec6d65,2023-01-05T00:00:00.000Z,2023-01-30T00:00:00.000Z,2023-01-30T00:00:00.000Z,True,89ea79cb-a445-4720-8368-b0887f4157bb,250.000000,0.0,1.0000,...,b918e8ad-5776-4da1-a74d-f3d9ca739f1f,Electricity,NaN,1.0,89ea79cb-a445-4720-8368-b0887f4157bb,Lumiere Electricity,True,False,NaN,NaN
29,271,31d35f2f-2211-449f-b203-7bb8ef345185,2023-02-05T00:00:00.000Z,2023-02-28T00:00:00.000Z,2023-02-28T00:00:00.000Z,True,89ea79cb-a445-4720-8368-b0887f4157bb,250.000000,0.0,1.0000,...,0bfc1f4f-a157-4266-9048-b0c0520ea7b6,Electricity,NaN,1.0,89ea79cb-a445-4720-8368-b0887f4157bb,Lumiere Electricity,True,False,NaN,NaN
30,272,23241525-7dd5-4d6a-b308-596315f29ce9,2023-03-05T00:00:00.000Z,2023-03-30T00:00:00.000Z,2023-03-30T00:00:00.000Z,True,89ea79cb-a445-4720-8368-b0887f4157bb,250.000000,0.0,1.0000,...,ed902368-c02d-4cf7-8293-cf56d6354f8a,Electricity,NaN,1.0,89ea79cb-a445-4720-8368-b0887f4157bb,Lumiere Electricity,True,False,NaN,NaN
31,273,4d87ce5a-66ff-4879-96a6-2182fdaba613,2023-04-05T00:00:00.000Z,2023-04-30T00:00:00.000Z,2023-04-30T00:00:00.000Z,True,89ea79cb-a445-4720-8368-b0887f4157bb,250.000000,0.0,1.0000,...,46766579-7e0f-434c-8f55-4e4c0bbdbad4,Electricity,NaN,1.0,89ea79cb-a445-4720-8368-b0887f4157bb,Lumiere Electricity,True,False,NaN,NaN
32,274,67d8db06-7429-4d43-bfdd-4f05821dc74c,2023-05-05T00:00:00.000Z,2023-05-30T00:00:00.000Z,2023-05-30T00:00:00.000Z,True,89ea79cb-a445-4720-8368-b0887f4157bb,250.000000,0.0,1.0000,...,1f708754-0584-44ff-b752-f05b3415f9bd,Electricity,NaN,1.0,89ea79cb-a445-4720-8368-b0887f4157bb,Lumiere Electricity,True,False,NaN,NaN
33,275,c034aa4d-6f26-4e3a-a888-634a281b02ce,2023-06-05T00:00:00.000Z,2023-06-30T00:00:00.000Z,2023-06-30T00:00:00.000Z,True,89ea79cb-a445-4720-8368-b0887f4157bb,250.000000,0.0,1.0000,...,8fd747a6-c03b-4520-9f87-1e302852c4c5,Electricity,NaN,1.0,89ea79cb-a445-4720-8368-b0887f4157bb,Lumiere Electricity,True,False,NaN,NaN
34,276,88519cb6-645a-4847-894d-b323d3f42349,2023-07-05T00:00:00.000Z,2023-07-30T00:00:00.000Z,2023-07-30T00:00:00.000Z,True,89ea79cb-a445-4720-8368-b0887f4157bb,250.000000,0.0,1.0000,...,cfe6fdea-bee0-4fe6-af60-82c6a7c952cc,Electricity,NaN,1.0,89ea79cb-a445-4720-8368-b0887f4157bb,Lumiere Electricity,True,False,NaN,NaN
35,277,4d7ec9e4-b378-48b6-89f5-6418bfa200b1,2023-08-05T00:00:00.000Z,2023-08-30T00:00:00.000Z,NaN,False,89ea79cb-a445-4720-8368-b0887f4157bb,250.000000,250.0,1.0000,...,edcd1d38-a497-4272-9cdf-3df3188faa90,Electricity,NaN,1.0,89ea79cb-a445-4720-8368-b0887f4157bb,Lumiere Electricity,True,False,NaN,NaN
36,253,da9f96b9-81ca-4e33-8108-336452e5540b,2021-12-14T00:00:00.000Z,2021-12-28T00:00:00.000Z,2022-01-25T00:00:00.000Z,True,89ea79cb-a445-4720-8368-b0887f4157bb,115.000000,0.0,1.0000,...,96035be3-873a-4b56-931e-a9c1251de85c,Electricity Increase once off payment,NaN,1.0,89ea79cb-a445-4720-8368-b0887f4157bb,Lumiere Electricity,True,False,NaN,NaN

In [28]:
merged2[merged2["description"] == 'Rental income']

,Unnamed: 0,id_invoice,issue_date,due_date,paid_date,paid,contact_id,total,amount_due,exchange_rate,...,id_invoice_info,description,item_code,quantity,id,name,is_supplier,is_customer,email,phone
0,0,90381d5a-9348-4208-915c-60b082378370,2021-01-31T00:00:00.000Z,2021-02-06T00:00:00.000Z,2021-02-06T00:00:00.000Z,True,8e81fbc4-4f33-4ae9-bf5e-a2415372e77b,174.8,0.0,1.0,...,a90834f9-90b5-4342-9cb6-f8d45b35fd7e,Rental income,NaN,1.0,8e81fbc4-4f33-4ae9-bf5e-a2415372e77b,Snow White,False,True,NaN,NaN
1,1,3dec381c-7af5-436d-8b35-2d3a69b95f89,2021-02-28T00:00:00.000Z,2021-03-06T00:00:00.000Z,2021-03-06T00:00:00.000Z,True,8e81fbc4-4f33-4ae9-bf5e-a2415372e77b,174.8,0.0,1.0,...,3554bf7d-bd10-449c-b05a-5a5e478bab73,Rental income,NaN,1.0,8e81fbc4-4f33-4ae9-bf5e-a2415372e77b,Snow White,False,True,NaN,NaN
2,2,0222b396-f017-4a90-ad5b-4a8e241d4afc,2021-03-31T00:00:00.000Z,2021-04-06T00:00:00.000Z,2021-04-06T00:00:00.000Z,True,8e81fbc4-4f33-4ae9-bf5e-a2415372e77b,174.8,0.0,1.0,...,1e35c6e6-456d-4dae-9d7f-c4ee6b15c06e,Rental income,NaN,1.0,8e81fbc4-4f33-4ae9-bf5e-a2415372e77b,Snow White,False,True,NaN,NaN
3,3,eb59789d-a21e-4628-a774-17a3bf38607b,2021-04-30T00:00:00.000Z,2021-05-06T00:00:00.000Z,2021-05-06T00:00:00.000Z,True,8e81fbc4-4f33-4ae9-bf5e-a2415372e77b,174.8,0.0,1.0,...,debf819e-83f7-41bf-9cef-1389fe2b5d94,Rental income,NaN,1.0,8e81fbc4-4f33-4ae9-bf5e-a2415372e77b,Snow White,False,True,NaN,NaN
4,4,87d4c9dc-f37a-43a2-8aab-40ba13f3a8ac,2021-05-31T00:00:00.000Z,2021-06-06T00:00:00.000Z,2021-06-06T00:00:00.000Z,True,8e81fbc4-4f33-4ae9-bf5e-a2415372e77b,174.8,0.0,1.0,...,f0e212e7-de75-4270-826f-50d5a75ce268,Rental income,NaN,1.0,8e81fbc4-4f33-4ae9-bf5e-a2415372e77b,Snow White,False,True,NaN,NaN
5,5,3de8e55e-25dd-4e0c-a1a0-c2108f82159b,2021-06-30T00:00:00.000Z,2021-07-06T00:00:00.000Z,2021-07-06T00:00:00.000Z,True,8e81fbc4-4f33-4ae9-bf5e-a2415372e77b,174.8,0.0,1.0,...,9631ade2-075b-4e58-9774-cc005279c61a,Rental income,NaN,1.0,8e81fbc4-4f33-4ae9-bf5e-a2415372e77b,Snow White,False,True,NaN,NaN
6,6,1af0d7c1-1109-441c-a259-d88fdbe9d2a0,2021-07-31T00:00:00.000Z,2021-08-06T00:00:00.000Z,2021-08-06T00:00:00.000Z,True,8e81fbc4-4f33-4ae9-bf5e-a2415372e77b,174.8,0.0,1.0,...,90302750-1222-433b-a108-f1541e8ec7fc,Rental income,NaN,1.0,8e81fbc4-4f33-4ae9-bf5e-a2415372e77b,Snow White,False,True,NaN,NaN
7,7,470d20c9-3dde-4d23-82b1-adc8bb0167f9,2021-08-31T00:00:00.000Z,2021-09-06T00:00:00.000Z,2021-09-06T00:00:00.000Z,True,8e81fbc4-4f33-4ae9-bf5e-a2415372e77b,174.8,0.0,1.0,...,b7d23ea3-9783-4355-a49f-87dba033e13f,Rental income,NaN,1.0,8e81fbc4-4f33-4ae9-bf5e-a2415372e77b,Snow White,False,True,NaN,NaN
8,8,a076018f-a612-4b83-aacf-04544babab37,2021-09-30T00:00:00.000Z,2021-10-06T00:00:00.000Z,2021-11-30T00:00:00.000Z,True,8e81fbc4-4f33-4ae9-bf5e-a2415372e77b,174.8,0.0,1.0,...,933f33c5-48b3-476d-9962-29bbcea48f9b,Rental income,NaN,1.0,8e81fbc4-4f33-4ae9-bf5e-a2415372e77b,Snow White,False,True,NaN,NaN
10,10,c1662564-34ef-419a-bc36-201e2f3a451c,2021-10-31T00:00:00.000Z,2021-11-06T00:00:00.000Z,2021-11-30T00:00:00.000Z,True,8e81fbc4-4f33-4ae9-bf5e-a2415372e77b,174.8,0.0,1.0,...,56e1b067-0b81-473f-923f-01a0a08913ce,Rental income,NaN,1.0,8e81fbc4-4f33-4ae9-bf5e-a2415372e77b,Snow White,False,True,NaN,NaN
11,11,03caaffa-82c8-4147-bc0a-4bfb1f608303,2021-11-30T00:00:00.000Z,2021-12-06T00:00:00.000Z,2021-12-06T00:00:00.000Z,True,8e81fbc4-4f33-4ae9-bf5e-a2415372e77b,174.8,0.0,1.0,...,526da924-d36d-4caf-aa1f-31454486ddb8,Rental income,NaN,1.0,8e81fbc4-4f33-4ae9-bf5e-a2415372e77b,Snow White,False,True,NaN,NaN
12,12,41e20ef0-b00b-4111-a0e5-5ebb45a0a23f,2021-12-31T00:00:00.000Z,2022-01-06T00:00:00.000Z,2021-01-06T00:00:00.000Z,True,8e81fbc4-4f33-4ae9-bf5e-a2415372e77b,174.8,0.0,1.0,...,6cdee755-7408-45d5-a58d-6d5d15af4618,Rental income,NaN,1.0,8e81fbc4-4f33-4ae9-bf5e-a2415372e77b,Snow White,False,True,NaN,NaN